### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Amirk390** [FACN3/al-forum#2]
creating a README file

**Comment by Amirk390** [comment]
the scheme diagram

![image](https://user-images.githubusercontent.com/24490876/33879685-de7c3e52-df37-11e7-912a-33346bf398b5.png)

**Comment by Amirk390** [comment]
Some changed need to be added to the README

+ add an architecture design
+ add the missing content in the **'About'** and **'Node packages'**

**Comment by Karyum** [comment]
@Amirk390 you dont need a section in the README for node packages or the languages that were used in the project ( you can see the languages under the repo name ).

also local installations guide are a bit lacking, i know it sounds dumb but you need for example to show to close the repo, cause you might have a product owner who does not know how to use github pr some shiz like that

**Comment by SamiSha99** [comment]
Woops, my bad I accidentally closed the issue when I thought nobody was going to reply to this.

**Comment by SamiSha99** [comment]
@Karyum I have updated the README file.

**Comment by Karyum** [comment]
good job can you send me the pull request link, well the pull request should have been related in this issue but i guess we will let it pass :stuck_out_tongue_winking_eye:

**Comment by SamiSha99** [comment]
https://github.com/FACN3/al-forum/commit/ad71d2e531d19371f37ac92808c3eca330888512

**Comment by Amirk390** [comment]
![sample-page](https://user-images.githubusercontent.com/24490876/34077755-57f9f136-e314-11e7-8c98-180cf1c94a4e.jpg)
