### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Karyum** [FACN3/al-forum#51]
# WHY YOU WORKING ON YOUR PROJECT

you should be opening issues on different people's project not closing your own!!

**Comment by SamiSha99** [comment]
[image](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANQAAADuCAMAAAB24dnhAAAA6lBMVEX/zE3////0kAxmRQD/zk5kQwD/z0//yDhiQQD/zEv/0lD0jghgPwD/ykPziQD/+/T/xzP/7cn1nT76x0r/+Or/9N7/79DzhgD/ykX+x0j/57f+9/L0wkddPAD/4qX/z1v/5Kz2nBv/68L1lhP/0mrsu0Phsj/7tzf8v0D4pCbYqjv/3JD7tTb/xiqwhyf/35r3tHeUbhrDmDD5rC7/137/1XSXcR1wTgr/0GDQoziEYBSlfST84Mv/9uSMZxv97+VzUAD5yJ/4u4X96dr/2of8w1b2pVP0lSX61bf2qmD1oEj3sW/3nwK4ji7hB0lRAAAQ6klEQVR4nO2dC1viOBfHC6Q3oIBTUeSiIlIFBQcYQdoZZC7v7Oy7L9//67xJi1japE3SlMs+/vfZ2WdWrflxTk5OTi6VMrtS3TDOdvSrpJSeW0Z6GqjvMiTJeP/b4Nr9jnR+eRpQp6en1cGagygXcPANfq94MsFQ5Wq1+k2PxvELkd1+q1bFgomEKp9VHyqwlTol0VrwM6g8nZ0J5BIHdXNyWTFqbDwb1YzK9cnJjaCmCIKq16/5iTwZhlG5EYMlAurmGoZr2l4UDabXr0+SNyg51MnllRgiJN0wXi4TD2dJoc4eXgzGwBDLdfv08G1/UKdfft0KRnKxasbzlyTBMAFU+fbWqIlH8riM29u9QElpEXlYtZernUPVpDSRXCxd57QWJ9RVRU+bSXKdcHdQXyo7IHJVqzxwRAwOqIdKstSBFespdahy9UndIRKSesmaxDNClS93aiZPMNlNE+rmctdm8qReM2W6TFAwE98LE6uxWKD2ZCZPKgMVPdTlXpmgsS6psaihLmv7cr0NlU5LRQt1uYsMIka6RElFCRXJBBQl75OigD1T0UGRmACkUbrWfOU409FisRiNRs5wNbeaCC0Vqiua2E4DVa9hmAAEAtbYWcxySPJG7l9ni+EckQmn0g2KGgYFVD2UkQP0T3dlF1ut4poiIFmDX1s6cxOg7xWKVYm3VTzUTSX0YNPsO7lWUcPh+MmKrZzTbyIwkarE2ioWKsQEmv3hslWMAXqTBrm6grFiqeKgwnZqOloR63IkFXOOZQqNiHFUMVAY3xvPmJBcrNnKMndIFQ1VDzEBy47rShjJxeWqKRBKio4WkVBhJklaMdvJlTYbi4SS1CiqKKg6JoPtTmlDRJBq1BXpgLpR54PCDbnWAu99sqxpRVeahh265GVf6FCsv3BB4XIj0B2FodyB1oYJEhJMmOwlGsTkINRcLFREHkiGwuZ7wFxtQ6EBdjScW91utwllmvCPLsoGp3As83PJI0twakGmIkIRctjt6FeEqVC/2zRhJghQOgi8URb+CeGsoe0bo+WV6NydTEWCIs815su1AWSUBJkmgsDASyibsoa5lvfdRbFxwqMizRoJUJfEFRogrVpQRWikcVy6Cg1njmewfxVbtpXCVMS4ZIQiPyoPTGu8Gs7pJhYK6Duj6dhMY3pFqsbgoeJqLHCuSz8JRNPitCbDeCos1J7rRizCZoE4qBNMdnSoMnCmwkCVozrUwUm9Dq8ehKHKR+R8SJXwSn4Y6tsROR8SJq6HoZ52v1aTTGpoVS4E9XBMHcpTJRbqyJwPqfYrBuqZ3/lAkhE2ULpmK14bX6KhOA0FlHyzP7eaPMVmiKM0rfl46EwXCxtqMZoyFq8rkVBXfGsbirSyZ0iLcZPFXqgW3+wPR+iHvfnze+kaPc5Z9U2aFCuwiyQAxTdE5cc5ryXwz+WYFgoSSf3p0vsxfIkA/W97aCn5mGqoLkVAsW5/9RrXtFvvjZJbI5Pqp0B3tWi1grP+sOC8ZTa1pOhJTu2KDMW136gbqAQWbYr5IJDgRIu2gihrLXvVjCqHbpdh/FBlHibQDdWXiqP4lQ4wnzEVReWW5lgR9dDaLQHqliecN52wA7WGsUGLo35Y1Jx+k/Rp6beneKhnHufDl9bjHFCZs1fkvaUG0hP9Y5UPqvrCDoVxPiR5GmMqZcyO5GItSLUO/bmKg/rCkfXp+MbJsxhTKXM+qJzmkOKF8YCBOrvl8D5i1xjmI38O9O1498ONXrJNqonqt2dhKJ70XOnPCO1ZRFsKNB1fnbNYzC3DD5JtWw6PYzNi9dp4CkHdcPQoSVoRDCXb3egfhKbyOiNst+2M+w7mIbN5fzVdFrfXLckl+ffZ4gbqiWce5f+8t6HIH+ib+ouiW+Vc9btNyVpgXE1zFLPZRSvMvmBEXjzRX26CUDzVFuwayPpTHsdAAak5d6ZwQHVXuVfY58wgACrL9x357cPTpuQQtFmyeoOqc2UTFrG7z1bRkcKVaZpuSkda9ZJHeRdfMrtDbe2tEesMunQTgOLxviioIc3Pr5NvUoDfODH8Ppg1azAHnEYtHb+Zag2FWwlNBJVbMCxHEbumf2TIj0dLexy5yB+AuuEqtwBs//Y+ZJpU/e0xxK4pL3ypMUVNfr1ov4a65oMiBwptQb/FAPSXhM+GPNTitd6N5UFh9oBQiew38pS+NUqf8BCKILotw6tBe1AnnMU+MCZOIGLyJL+UObFnMkJJlbMNVJm3KquQHIdi8PU9Zd4iQq3YoIzqBuqMu4LZJfhfbJrklzIn9Uymzwap9lTeQPGXmseEjHbIUiiLCBSsy9+V6htUlRsKxj+cqWLnU9sPIQ53ss26TUv9toY6TVBrxk/n5fgihV/dKXGcYq341tAJTQRVTbDKBkxM4UWzqUp/G5mkGUzOoY+ha1VOk0PhqhSy3GX7gJU5oWeyRnQodQ31Ldl6aLCYKWusvZuYpc/Y9zOtoU65is2+JnWXfu9pLdk37Oj4+ZS8YPY+SS2voZh/cluKOX0r8cP/DHX25RyFEP94dtMNykKg4LTAstFazGxmD7t8S29DnKFsnkepoqDgtKA7Hg7HfTPPt5oIxzuMqbg2aXlQvNlsoFlouxL/pvr8PJRVaOzxHMmFKg94GyJUIJhwyVO+rexwTgWhDmODC1DG/mAhyw7vRvbB4UChJatRzitcyrJmD7k356uHBCXBYOPYcOzOLRfDPv8xisOCgi7YtOZQfSvJOR4Exbkin5LcIJogikoeVJJ5x0EKQR3hZqRo6c/SYXmfEOn/RijpA+po9AF1LPqAOhZ9QB2Ljm5vPY0SrHgcrv6V7vcBdSz6gDoWfUAdiz6gjkM1KZPu+oB3+0GqvyKo2qXEtc9UUi7uoaKOdHhLOxK6oMI03/62E/GWne8nvTbU5PEC31BF6lr9+Xjl3iTioCtFVuN532qCXZDxQSl37YKnbO/uIvx1YI6d6cJeztCtL+ubX+Tc0l5MndXcAuKvXdsWFxSATNm1Cp1e2FjN6ayohU+vobttIJoz7DfjTq4lEhfURW/DhNS+D3w970QcX5PXKzUS19Inlbig7ttbUIV2wAO7hO0rPrDcbLHiXMaP14BjzRc8drLZbaqtrxP35AS5nHSw1FOOLQdgks1GUdGeIoKdbtpNwQm59lGELAWpJv6vWxSW8qS1RkKvXXMlCipb8geLPHFfNwZLG5qC75+seFCMh4zu2iGoLQeEpmI4GFq0E6xZY6S/lHm2xgVCukd152tYfr7Mwaguo4FpI/yha2Ss3LAp0Fgq385MJRQpgrEibzkwoViik/1QDvx3tLDtWS5065orWRv1hTFtNjFW2ZZ9wV24U2WzW0MwULp9mOyhW8r0fD6vm82uBVNBZ2TncHeiavZcmAu+QZUf2Kq0F+2w/2V7gYzO2ziwbirwLpyQIOpwsQzfI6otx2y7bsl620PLvIW7h7FUB5PZhqUopjUfQnsFqWaCqIzLMt9m+/Dwi6Du6BwIAMg1hilv2FYiPHCzL531WAS+UwX9L+LnAfRDJ4ClzebMBBi9nyAoMx6fusdABTLAWDX709xWzNAWAkzlnXXjOmp00cGMVJ3gFCRO5tzeMlZLwLWGxvtRI9ZDYdjwR9upfGo6vitHci0Bl2r6zk+xHh5VcFDZCXObALB8cVCApbaO74mAKtBHCt+T9E32Ky+TZ+zbUDdMZ5fxUG2ukQY4ufUW02HiQKFLZwkOL+OhqIbfsFY22qe/HBKvOqGWETiRzXTJATZQFEIVGDoB4O7Tvxcw9AYOL7NdCHCPCeko/PE2RlD5dnPNBs/VDfiMItt53G3NPKTN/ZkbKIbbULC5H9Seod6vruG6DgUz9UWWYh+ohApzc0imSn1t0j127OUZfYUKc8cL/RVDuOn8AUDVvpxioE4pexWu8HIA7oe9N4n2LjJC7BMRKNzTA5wLPTXfK1i3rsKjGoBJhkrofkC5uOu1O51Oj28MJ9xFlslc0ZiK1KMSjFNA0e8mbom0kEUreYT1ySjpzxkCFMWlhWTnyzLPEiXvAvyLu0nHXZZ8E0/CVSNDxYcKUjhHTWE8LgyBLhBQqRB8ZKHHmhuTb2LMxN/YSmZinU9dXNxDlyuEgLxnPbJC/YqA+hLdqyKYWLoUBHrskYA8q7OZStczEVDRW0Xw2fm6HVTVTLAGypKBvE+IrVcF7qwOQkVUoGGMiGpJrPcB1+NcoGiiLKv/1QL3cIcurCaaCjxGMsV8tpDnkRLIhZqw+N8gEwNFutcePGYjmzMhGQqOqhAIjqu0QC4US/wLvYcgfAk8vlqLWxT1NwLfsxEQMlAnrg9hoOgH4EHwLQSU1/XrxDxi3YhwiQEBTXocQO7zGNwv/NYwzNsiMDfIxTGVtvs1AMCNcUwetw1FHyiM8DvDcO/1CJXLYu3k23IAUGY6mXQ62eg+GP1AhpA+qFJBBV9WojzGNOGtVwNFgl2ojXofP5D7RHpD4V7Bgn2tTH37vfLRsRw24cIFAptMO6EKW5tNooV9FSn+BUB135uaYsZc1IieLt27iWliHvS0bOeOOovEv181/lVNsUywHSVhQNlO+45+V4WuY98CSYB6v+wUW2JOQ/BTgdPeuwuGXH9znSkd1DvVZBdMCKjdnkAiljmvTnpjMfFFdR6V/pg6kwvUg0CAdQ+qEXqfTBxUpo5eh4FbshYKVHCB7iWOBYLaFem1qhEvf0S1JWLlSCAQm89tpBOZoqBODP2ulBpQtt175AaS3lcNGaEyZ0Yake8dKMk+bt0gM0W/+vZ/wpkgURt53EXSHX6VcMZHCXUumqkzeYRAOvYdmEzCZLG0UMJ7VJt9AwkHUyTUpxR6FHHWzyI1/G46aqjk+XZYhXZiKl0dnEa0OgbqrzQGKa6NMVtMRrTvRUOlwrSefSVg0iNieTxUGl0KQfWSBAv9Kp5pD1DZTgImcr63byiONTUmpuOyFCXTMUHpBiVTBNSftKJfh8/79NoNJVME1O+0plKcw69KEfb2BlXgWsQ3BvRMEVD/PaQuVTmLTSOooBrpBAqeNMkY0PamOKiUol+Jfftw5Sb8GuyDgiqx9ijdGNTJbTwIKNYooes13DvYDwqKde9wLbjufoBQjHuOavozF9NuoQodhqXcmvEr+O5rAVA/RDNlGbYS1IwHXqTdT+fppog19Ref4+0HavtEOla6of66ZhyZ6KGELA4GFZdR6OrzTT2mWpQE6ms6ywMRex2hkV5OWLI8dijxFVqkAtH/DFWtMiWuhwOVxUMZ6uCsKoIoDkr4AgEBqqaqg/ppwo5EC9VIhWobSlfVykOmnCjaMUGlYqqCgvJUVyoEim5AGlApUMHRV1/HP1WoeaihUvC/0n9erh4if2nqUMKT2sKnlIHioYSbqvR7B0yxUH+LNFWh9PcumOKgMq8CTVX4/KNxEFCNz+LSisKPnSDFQ0EqcQ5Y+rwLJAqozFeBDlj6nNbQtKV4qMYPgXnt+U46FUWW0vghzgEPBirzXZwDHg5URpwDHhBURlhcPySojKC4XigdEpQgqt0Yihoq848AqsJfr2mybEQ/8UzerwqfdsPEAAWpEh61+b0jJhaozI8kob1Q+v0zNYqA2OoeP845jQWRvu+MiRGq8Z3HWKVS6dOfrykB4MRaoWp8ZjIW5Cmdf/2zUyR2qEzj6z+UWAXI8/0rVBrtjhRHLfH15+/zmEBYQAb65+fPn7sZbIPiKpA2XhuFc2LnKp2flxqvr6/7AULirfo2Gq/nOC5I9LPR2B+Pq0Sl7J8hqtLuOxBG/weYc9xT40RzAgAAAABJRU5ErkJggg==)

**Comment by SamiSha99** [comment]
![download](https://user-images.githubusercontent.com/29677942/33983792-1b5f091c-e0be-11e7-8536-25dd07d43624.png)
