### ISSUE TITLE
Forum posts act strangely below 600px width

### ISSUE THREAD

**Issue by NickP123** [FACN3/al-forum#57]

**Comment by SamiSha99** [comment]
I'm so dissapointed in you Nick, at least provide a description implying their is no sort of a **message frame border**.

Oh and it's 500px, not 600px.

**Comment by NickP123** [comment]
I'm more concerned that you are responding to my issue rather than raising issues on other peoples projects...

**Comment by SamiSha99** [comment]
We already filed all our issues, we couldn't access their site, so we moved to other projects.

No need to be concerned.

**Comment by Amirk390** [comment]
@Nick Thanks,
fixed :smile:
