### ISSUE TITLE
plaintext passwords in the sql file

### ISSUE THREAD

**Issue by Karyum** [FACN3/al-forum#67]
https://github.com/FACN3/al-forum/blob/master/src/database/db_build.sql#L18-L22

ummm? i see someone's username and password there **in plaintext**

**Comment by SamiSha99** [comment]
Oh, that was to test if the database works, that was before we added the hash, we are going to remove it soon.

**Comment by sophiavocado** [comment]
already deleted before! :)

**Comment by Karyum** [comment]
@sophieeejw nice !
