### ISSUE TITLE
Switch the names for Router and Handler files - NOT A BIG ISSUE but it helps others

### ISSUE THREAD

**Issue by MarlenAw** [FACN3/al-forum#68]
handler.js is where you handle all the functions..so whats in the router should be in handler..and whats in handler should be in router.

NOT A BIG ISSUE but it helps others find you code easily

**Comment by ghassanmas** [comment]
handler.js is suppose to handle all the static files requests like .js .html .css ..etc. Yeah it would be more clear it was called staticHandler.js
